version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - 5432:5432

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: deveduardomelo@gmail.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - 8080:80
    depends_on:
      - db
